print('=== DESAFIO 04 ===')
algo = input('Digite algo: ')
print('Você digitou: {}'.format(algo), ',o tipo primitivo dele é', type(algo))
print('Informações adicionais abaixo')
print('Só tem espaços?',format(algo).isspace())
print('É númerico?',format(algo).isnumeric())
print('Está em minúsculo?',format(algo).islower())
print('Está em maiusculo?',format(algo).isupper())
print('Tem letra?',format(algo).isalpha())
print('É decimal?',format(algo).isdecimal())
print('É alfanumérico?',format(algo).isalnum())
print('=== Fim do código ===')
